// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXrYv9xk4KNOaoaokuNKx2DX7369mtDmg',
    appId: '1:695262628164:web:23058603a4391b01aeef11',
    messagingSenderId: '695262628164',
    projectId: 'skipq-appdev',
    authDomain: 'skipq-appdev.firebaseapp.com',
    storageBucket: 'skipq-appdev.firebasestorage.app',
    measurementId: 'G-XETDZ9GJ66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3kSFXHbkskrLacvhVHwT9XxIC2AZQexI',
    appId: '1:695262628164:android:5fca80b1373ae092aeef11',
    messagingSenderId: '695262628164',
    projectId: 'skipq-appdev',
    storageBucket: 'skipq-appdev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjE943r-q38008JeqsDTRImlP4gxwgcYE',
    appId: '1:695262628164:ios:d2631fc31e5877baaeef11',
    messagingSenderId: '695262628164',
    projectId: 'skipq-appdev',
    storageBucket: 'skipq-appdev.firebasestorage.app',
    iosBundleId: 'com.example.skipq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjE943r-q38008JeqsDTRImlP4gxwgcYE',
    appId: '1:695262628164:ios:d2631fc31e5877baaeef11',
    messagingSenderId: '695262628164',
    projectId: 'skipq-appdev',
    storageBucket: 'skipq-appdev.firebasestorage.app',
    iosBundleId: 'com.example.skipq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXrYv9xk4KNOaoaokuNKx2DX7369mtDmg',
    appId: '1:695262628164:web:e73b7c95f74d1c7caeef11',
    messagingSenderId: '695262628164',
    projectId: 'skipq-appdev',
    authDomain: 'skipq-appdev.firebaseapp.com',
    storageBucket: 'skipq-appdev.firebasestorage.app',
    measurementId: 'G-MPXL3R3J3L',
  );
}
